
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ENNEMIS-G
 */
public class Tugas extends javax.swing.JFrame {

    /**
     * Creates new form Tugas
     */
    public Tugas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nilai1 = new javax.swing.JTextField();
        txt_nilai2 = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_kurang = new javax.swing.JButton();
        btn_kali = new javax.swing.JButton();
        btn_bagi = new javax.swing.JButton();
        txt_hasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NILAI 1 :");

        jLabel2.setText("NILAI 2 :");

        txt_nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nilai1ActionPerformed(evt);
            }
        });
        txt_nilai1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nilai1KeyTyped(evt);
            }
        });

        btn_tambah.setText("+");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_kurang.setText("-");
        btn_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kurangActionPerformed(evt);
            }
        });

        btn_kali.setText("x");
        btn_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaliActionPerformed(evt);
            }
        });

        btn_bagi.setText(":");
        btn_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bagiActionPerformed(evt);
            }
        });

        txt_hasil.setText("HASIL ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nilai1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_hasil)
                            .addComponent(txt_nilai2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_kurang))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_kali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_bagi)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_kurang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kali)
                    .addComponent(btn_bagi))
                .addGap(31, 31, 31)
                .addComponent(txt_hasil)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nilai1ActionPerformed
                                                 
         String nilai2 = txt_nilai2.getText();// TODO add your handling code here:
    }//GEN-LAST:event_txt_nilai1ActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed

        try{int nilai1= Integer.parseInt(txt_nilai1.getText());// inputan nilai yang pertama
int nilai2 = Integer.parseInt(txt_nilai2.getText());// ini yang ke 2
int hasil =nilai1 + nilai2;
txt_hasil.setText(String.valueOf(hasil));
} catch (NumberFormatException e) {
        JOptionPane.showConfirmDialog(null, "MASUKAN BERUPA ANGKA \nMOHON PERIKSA INPUTAN", "PERHATIAN", JOptionPane.CANCEL_OPTION);// input validasi
    txt_nilai1.setText("");
   txt_nilai2.setText("");
    txt_hasil.setText("");
   }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kurangActionPerformed
try{
        int nilai1= Integer.parseInt(txt_nilai1.getText());// input pertama
int nilai2 = Integer.parseInt(txt_nilai2.getText());// yang ke 2
int hasil =nilai1 - nilai2;
txt_hasil.setText(String.valueOf(hasil)); 

} catch (NumberFormatException e) {
        JOptionPane.showConfirmDialog(null, "MASUKAN BERUPA ANGKA \nMOHON PERIKSA INPUTAN", "PERHATIAN", JOptionPane.CANCEL_OPTION);// input validasi
    txt_nilai1.setText("");
   txt_nilai2.setText("");
    txt_hasil.setText(""); 
}// TODO add your handling code here:
    }//GEN-LAST:event_btn_kurangActionPerformed

    private void btn_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaliActionPerformed
  try {   
int nilai1= Integer.parseInt(txt_nilai1.getText());// inputan pertama
int nilai2 = Integer.parseInt(txt_nilai2.getText());// yang kedua
int hasil =nilai1 * nilai2;
txt_hasil.setText(String.valueOf(hasil)); 

    } catch (NumberFormatException e) {
        JOptionPane.showConfirmDialog(null, "MASUKAN BERUPA ANGKA \nMOHON PERIKSA INPUTAN", "PERHATIAN", JOptionPane.CANCEL_OPTION);// input validasi
    txt_nilai1.setText("");
   txt_nilai2.setText("");
    txt_hasil.setText("");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btn_kaliActionPerformed

    private void btn_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bagiActionPerformed

        try{
double nilai1= Double.parseDouble(txt_nilai1.getText())  ; // inputan pertama
double nilai2= Double.parseDouble(txt_nilai2.getText())  ; //ke 2
double hasil = nilai1 / nilai2;

txt_hasil.setText(Double.toString(hasil)) ;
txt_hasil.setText(String.format("%.2f",hasil));//pembatas agar hanya 2 angka di belakang koma
 } catch (NumberFormatException e) {
        JOptionPane.showConfirmDialog(null, "MASUKAN BERUPA ANGKA \nMOHON PERIKSA INPUTAN", "PERHATIAN", JOptionPane.CANCEL_OPTION);// input validasi
    txt_nilai1.setText("");
   txt_nilai2.setText("");
    txt_hasil.setText("");}
// TODO add your handling code here:
    }//GEN-LAST:event_btn_bagiActionPerformed

    private void txt_nilai1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nilai1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nilai1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bagi;
    private javax.swing.JButton btn_kali;
    private javax.swing.JButton btn_kurang;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txt_hasil;
    private javax.swing.JTextField txt_nilai1;
    private javax.swing.JTextField txt_nilai2;
    // End of variables declaration//GEN-END:variables
}
